version: "3"
services:
  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    network_mode: host
    ports: 
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml --web.enable-admin-api --web.listen-address=:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    container_name: grafana
    network_mode: host
    image: grafana/grafana:7.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
  grafana-dashboards:
    container_name: grafana-dashboard
    depends_on: [grafana]
    network_mode: host
    image: alpine
    volumes:
      - ./grafana-data:/grafana
    command: >
      /bin/sh -c "
        apk add --no-cache curl
        echo 'waiting for grafana'
        sleep 5s
        cd /grafana
        curl --request POST http://localhost:3000/api/datasources --header 'Content-Type: application/json' -d @datasources.json
        curl --request POST http://localhost:3000/api/dashboards/db --header 'Content-Type: application/json' -d @dashboard.json"