{
 "title": "Monitor.py",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Throughput / Goodput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "tcp_throughput+udp_throughput+icmp_throughput",
     "legendFormat": "Total throughput"
    },
    {
     "expr": "tcp_goodput+udp_goodput+icmp_goodput",
     "legendFormat": "Total goodput"
    }
   ]
  },
  {
   "title": "TCP Throughput/ Goodput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "tcp_throughput", "legendFormat": "TCP Throughput" },
    { "expr": "tcp_goodput", "legendFormat": "TCP Goodput" }
   ]
  },
  {
   "title": "UDP Throughput/ Goodput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "udp_throughput", "legendFormat": "UDP Throughput" },
    { "expr": "udp_goodput", "legendFormat": "UDP  Goodput" }
   ]
  },
  {
   "title": "ICMP Throughput/ Goodput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "icmp_throughput", "legendFormat": "ICMP Throughput" },
    { "expr": "icmp_goodput", "legendFormat": "ICMP Goodput" }
   ]
  },
  {
   "title": "TCP Jitter (STDDEV)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tcp_jitter_stddev", "legendFormat": "TCP Jitter" }
   ]
  },
  {
   "title": "Average Inter-arrival time TCP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tcp_jitter_avg", "legendFormat": "Average Inter-arrival time" }
   ]
  },
  {
   "title": "Total sequence errors",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "tcp_total_err", "legendFormat": "Total sequence errors TCP" },
    { "expr": "udp_total_err", "legendFormat": "Total sequence errors UDP" },
    { "expr": "icmp_total_err", "legendFormat": "Total sequence errors ICMP" }
   ]
  },
  {
   "title": "UDP Jitter (STDDEV)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "udp_jitter_stddev", "legendFormat": "UDP Jitter" }
   ]
  },
  {
   "title": "Average Inter-arrival time UDP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "udp_jitter_avg", "legendFormat": "Average Inter-arrival time" }
   ]
  },
  {
   "title": "ICMP Jitter (STDDEV)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "icmp_jitter_stddev", "legendFormat": "ICMP Jitter" }
   ]
  },
  {
   "title": "Average Inter-arrival time ICMP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "icmp_jitter_avg", "legendFormat": "Average Inter-arrival time" }
   ]
  },
  {
   "title": "Packet drop statistics TCP",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "tcp_total_err", "legendFormat": "Total Sequence Errors" },
    { "expr": "tcp_reverse_err", "legendFormat": "Reverse Errors" },
    { "expr": "tcp_small_err", "legendFormat": "Small Errors" },
    { "expr": "tcp_big_err", "legendFormat": "Big Errors" }
   ]
  },
  {
   "title": "Packet drop statistics UDP",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "udp_total_err", "legendFormat": "Total Sequence Errors" },
    { "expr": "udp_reverse_err", "legendFormat": "Reverse Errors" },
    { "expr": "udp_small_err", "legendFormat": "Small Errors" },
    { "expr": "udp_big_err", "legendFormat": "Big Errors" }
   ]
  },
  {
   "title": "Packet drop statistics ICMP",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "icmp_total_err", "legendFormat": "Total Sequence Errors" },
    { "expr": "icmp_reverse_err", "legendFormat": "Reverse Errors" },
    { "expr": "icmp_small_err", "legendFormat": "Small Errors" },
    { "expr": "icmp_big_err", "legendFormat": "Big Errors" }
   ]
  }
 ]
}